export const SELECT_DATE = "SELECT_DATE";
export const GET_CURRENT_MONTH = "GET_CURRENT_MONTH";

export const OPEN_POP_OVER = "OPEN_POP_OVER";
export const CLOSE_POP_OVER = "CLOSE_POP_OVER";

export const OPEN_REMINDER_LIST = "OPEN_REMINDER_LIST";
export const CLOSE_REMINDER_LIST = "CLOSE_REMINDER_LIST";

export const SET_ANCHOR_EL = "SET_ANCHOR_EL";

export const ADD_REMINDER = "ADD_REMINDER";
export const EDIT_REMINDER = "EDIT_REMINDER";
export const DELETE_REMINDER = "DELETE_REMINDER";


